Update nexjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -35,19 +35,17 @@ jobs:
         id: detect-package-manager
         run: |
           if [ -f "/home/runner/work/Toll-Calculator/Toll-Calculator/yarn.lock" ]; then
-    echo "manager=yarn" >> $GITHUB_OUTPUT
-    echo "command=install" >> $GITHUB_OUTPUT
-    echo "runner=yarn" >> $GITHUB_OUTPUT
-    exit 0
-  elif [ -f "/home/runner/work/Toll-Calculator/Toll-Calculator/package.json" ]; then
-    echo "manager=npm" >> $GITHUB_OUTPUT
-    echo "command=ci" >> $GITHUB_OUTPUT
-    echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-    exit 0
-  else
-    echo "Unable to determine package manager"
-    exit 1
-  fi
+            echo "manager=yarn" > $GITHUB_ENV
+            echo "command=install" > $GITHUB_ENV
+            echo "runner=yarn" > $GITHUB_ENV
+          elif [ -f "/home/runner/work/Toll-Calculator/Toll-Calculator/package.json" ]; then
+            echo "manager=npm" > $GITHUB_ENV
+            echo "command=ci" > $GITHUB_ENV
+            echo "runner=npx --no-install" > $GITHUB_ENV
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
